# Generated by Django 4.0.5 on 2022-09-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountainpens', '0002_brand_fountainpen_inkreservior_inkreserviortype_nib_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inkreservior',
            old_name='reservior_model',
            new_name='reservior_brand',
        ),
    ]
