# Generated by Django 4.0.5 on 2022-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountainpens', '0003_rename_reservior_model_inkreservior_reservior_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='fountainpen',
            name='color',
            field=models.CharField(default='RED', max_length=50),
        ),
    ]
